name: 'Crust File Replica'
description: 'Get your file replica on Crust Network'
author: 'crust'
branding:
  icon: 'book'
  color: 'orange'

inputs:
  cid:
    description: 'IPFS cid which should be provided to Crust'
    required: true
  crust-endpoint:
    description: 'Crust Chain websocket endpoint'
    required: false
    default: 'wss://rpc.crust.network'
  file-replica:
    description: 'Minimal file replica to return'
    required: false
    default: 10
  max-attempts:
    description: 'Maximum attempts to get file replica'
    required: false
    default: 1

outputs:
  replicaCount:
    description: 'File replicas count on Crust'

runs:
  using: 'node12'
  main: 'dist/index.js'
